#!/usr/bin/env python
"""
render-docx.py — render a generated resume.md to an ATS-safe single-column .docx

Why this exists: the pipeline used to stop at markdown. Research (2026-05-30) found that a
single-column .docx is the safest-parsing format across ATS — and the only one Oracle Taleo
(Big-4 / Deloitte lineage) handles reliably. This makes .docx the default workflow output.

ATS-safety rules enforced here:
  - single column, left-aligned, no tables / text boxes / columns / graphics
  - contact info in the BODY, never in a header/footer (ATS strip headers ~25% of the time)
  - standard section headings (EXPERIENCE / EDUCATION / ...), bold + a thin bottom rule
  - standard font (Calibri 10.5), 0.6" margins
  - generator scaffolding lines (the `# Title` and `*Tailored… Generated by…*`) are dropped

Usage:
    python tools/render-docx.py --md applications/FOLDER/resume.md
    python tools/render-docx.py --md applications/FOLDER/resume.md --out some/path.docx
"""

import argparse
import re
import sys
from pathlib import Path

try:
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except ImportError:
    print("ERROR: python-docx not installed. Run: python -m pip install python-docx")
    sys.exit(1)

FONT = "Calibri"

# Typographic Unicode -> ASCII. Legacy parsers (Taleo / Big-4 lineage) can turn these into
# question marks; the research (2026-05-30) flagged Unicode symbols as a parse risk. The .docx
# is the ATS artifact, so we harden it. The source markdown keeps the pretty glyphs.
_ASCII_FOLD = {
    "–": "-", "—": "-", "−": "-",        # – — − dashes
    "·": "|", "•": "-",                          # · • separators/bullets
    "→": "->", "←": "<-",                        # → ← arrows (e.g. "Level I -> Lead")
    "’": "'", "‘": "'", "“": '"', "”": '"',  # curly quotes
    "…": "...", " ": " ",                        # ellipsis, nbsp
}


def ascii_harden(text: str) -> str:
    for u, a in _ASCII_FOLD.items():
        text = text.replace(u, a)
    return text


# ---------------------------------------------------------------------------
# Inline markdown -> runs (**bold**, *italic*)
# ---------------------------------------------------------------------------
_INLINE = re.compile(r"(\*\*.+?\*\*|\*.+?\*)")


def add_runs(paragraph, text, size=10.5, base_bold=False):
    """Add text to a paragraph, honoring **bold** and *italic* inline markers."""
    for tok in _INLINE.split(text):
        if not tok:
            continue
        if tok.startswith("**") and tok.endswith("**"):
            run = paragraph.add_run(tok[2:-2])
            run.bold = True
        elif tok.startswith("*") and tok.endswith("*"):
            run = paragraph.add_run(tok[1:-1])
            run.italic = True
        else:
            run = paragraph.add_run(tok)
            run.bold = base_bold
        run.font.name = FONT
        run.font.size = Pt(size)


def _bottom_border(paragraph):
    """Add a thin bottom rule to a paragraph (the section-header underline)."""
    p = paragraph._p
    pPr = p.get_or_add_pPr()
    pbdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "808080")
    pbdr.append(bottom)
    pPr.append(pbdr)


def _tight(paragraph, before=2, after=2):
    pf = paragraph.paragraph_format
    pf.space_before = Pt(before)
    pf.space_after = Pt(after)
    pf.line_spacing = 1.0


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------
def render(md_path: Path, out_path: Path) -> Path:
    lines = md_path.read_text(encoding="utf-8").splitlines()

    doc = Document()
    for section in doc.sections:
        section.top_margin = section.bottom_margin = Inches(0.6)
        section.left_margin = section.right_margin = Inches(0.7)
    normal = doc.styles["Normal"]
    normal.font.name = FONT
    normal.font.size = Pt(10.5)

    # State: drop the leading generator scaffolding (H1 + the *Tailored…Generated by…* line)
    name_done = False
    i = 0
    n = len(lines)
    while i < n:
        raw = lines[i]
        line = ascii_harden(raw.strip())
        i += 1

        if not line or line == "---":
            continue
        if line.startswith("# "):                       # generator H1 role title — drop
            continue
        if line.startswith("*") and ("Generated by" in line or "Tailored for" in line):
            continue                                     # generator metadata line — drop

        # Name (first **bold** standalone line)
        if not name_done and line.startswith("**") and line.endswith("**"):
            p = doc.add_paragraph()
            _tight(p, before=0, after=0)
            r = p.add_run(line[2:-2])
            r.bold = True
            r.font.name = FONT
            r.font.size = Pt(17)
            name_done = True
            continue

        # Contact/tagline (italic line right after the name)
        if name_done and line.startswith("*") and line.endswith("*") and "|" not in line and "## " not in line:
            # only treat as contact if it is the line immediately following the name block
            if not any(seg in line for seg in ("EXPERIENCE", "EDUCATION")):
                p = doc.add_paragraph()
                _tight(p, before=0, after=6)
                add_runs(p, line, size=9.5)
                continue

        # Section header
        if line.startswith("## "):
            p = doc.add_paragraph()
            _tight(p, before=8, after=3)
            r = p.add_run(line[3:].upper())
            r.bold = True
            r.font.name = FONT
            r.font.size = Pt(11)
            r.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)
            _bottom_border(p)
            continue

        # Bullet
        if line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            _tight(p, before=1, after=1)
            add_runs(p, line[2:], size=10.5)
            continue

        # Everything else: a normal paragraph (company lines, prose, competency labels, certs).
        # add_runs handles the **bold** company / **Label:** and any *italic* title inline.
        p = doc.add_paragraph()
        _tight(p, before=2, after=2)
        add_runs(p, line, size=10.5)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))
    return out_path


def main():
    ap = argparse.ArgumentParser(description="Render resume.md to an ATS-safe single-column .docx")
    ap.add_argument("--md", required=True, help="Path to a generated resume.md")
    ap.add_argument("--out", help="Output .docx path (default: FOLDER/exports/dustin-winkler-resume.docx)")
    args = ap.parse_args()

    md_path = Path(args.md)
    if not md_path.exists():
        print(f"ERROR: resume.md not found: {md_path}")
        sys.exit(1)

    if args.out:
        out_path = Path(args.out)
    else:
        out_path = md_path.parent / "exports" / "dustin-winkler-resume.docx"

    result = render(md_path, out_path)
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print(f"[OK] Rendered ATS-safe .docx: {result}")
    # Auto-sign exports/ so pre-submit-check can verify integrity
    try:
        import subprocess as _sp
        _sp.run([sys.executable, str(Path(__file__).parent / "sign-exports.py"),
                 str(result.parent.parent)], check=False, capture_output=True)
    except Exception:
        pass


if __name__ == "__main__":
    main()
