#!/usr/bin/env python
"""
sign-exports.py — compute SHA256 of every file in an application's exports/ folder
and write (or update) exports/checksums.sha256.

Called automatically at the end of generate-resume.py and render-docx.py so the
pre-submit-check can verify nothing changed between generation and submission.

Usage:
    python tools/sign-exports.py applications/FOLDER
    python tools/sign-exports.py applications/FOLDER/exports    # same thing

Exit codes: 0 = signed, 1 = folder not found.
"""
import hashlib
import os
import stat
import sys
from datetime import datetime
from pathlib import Path


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sign(app_folder: Path) -> Path:
    exports = app_folder if app_folder.name == "exports" else app_folder / "exports"
    if not exports.exists():
        raise FileNotFoundError(f"exports/ not found under {app_folder}")

    checksum_file = exports / "checksums.sha256"
    signed_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# checksums.sha256 - generated by sign-exports.py",
        f"# signed: {signed_at} (local time)",
        "# line format: <sha256>  <filename>  # modified: <YYYY-MM-DD HH:MM:SS>",
    ]
    for f in sorted(exports.iterdir()):
        if f.name == "checksums.sha256" or not f.is_file():
            continue
        modified = datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S")
        lines.append(f"{sha256_file(f)}  {f.name}  # modified: {modified}")

    # The manifest may be read-only in a locked folder; clear that flag so re-signing works.
    if checksum_file.exists():
        try:
            os.chmod(checksum_file, stat.S_IWRITE)
        except OSError:
            pass
    checksum_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return checksum_file


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if len(sys.argv) < 2:
        print("Usage: sign-exports.py <application-folder>")
        sys.exit(1)

    folder = Path(sys.argv[1])
    if not folder.exists():
        print(f"ERROR: folder not found: {folder}")
        sys.exit(1)

    try:
        cf = sign(folder)
        count = len([l for l in cf.read_text(encoding="utf-8").splitlines()
                     if l.strip() and not l.startswith("#")])
        print(f"[OK] Signed {count} file(s): {cf}")
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
